#!/bin/bash

printf "\n----------------Users-----------------------\n"
cat /etc/passwd | cut -d: -f1 | pr -s' ' -5 -l1 -t | awk '{printf "%10s  %10s  %10s  %10s  %10s\n", $1, $2, $3, $4, $5}' 
printf "\n----------------End------------------------\n"

printf "\n----------------Groups-----------------------\n"
groups

printf "\n----------------Users logged in on computer-----------------------\n"
users
